### ISSUE TITLE
Switch to GitHub Releases

### ISSUE THREAD

**Issue by stefan-balke** [conda-forge/libsndfile-feedstock#3]
Hey,

the project is now on maintained on GitHub.
Maybe the recipe should switch the .tar.gz URL:
https://github.com/erikd/libsndfile/releases

**Comment by mgeier** [comment]
I don't think this is a good idea, because those files have quite different contents:

* http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28.tar.gz
* https://github.com/erikd/libsndfile/archive/1.0.28.tar.gz

For starters, the file `configure` isn't available in the second one.

The first one is the official release tarball, created by the author.
The second one just holds a snapshot of the repo, automatically created by Github.

**Comment by stefan-balke** [comment]
Oh, maybe @erikd might clarify this. I guess that should not happen...

**Comment by erikd** [comment]
The official release files are on www.mega-nerd.com. I don't support the repo snapshots created by Github.

**Comment by thomasfillon** [comment]
Ok thank you all for your clear explanation and clarification about this.

**Comment by SylvainCorlay** [comment]
@erikd quick bot on release files: there are means to upload generated tarballs as github releases. Libzmq for example does that.
